'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidade de salvamento automático do My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ORACLE")>  _
        Public Property BaseOrigem() As String
            Get
                Return CType(Me("BaseOrigem"),String)
            End Get
            Set
                Me("BaseOrigem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PATIODEV")>  _
        Public Property ServidorOrigem() As String
            Get
                Return CType(Me("ServidorOrigem"),String)
            End Get
            Set
                Me("ServidorOrigem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OPERADOR")>  _
        Public Property SchemaOrigem() As String
            Get
                Return CType(Me("SchemaOrigem"),String)
            End Get
            Set
                Me("SchemaOrigem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OPERADOR")>  _
        Public Property UsuarioOrigem() As String
            Get
                Return CType(Me("UsuarioOrigem"),String)
            End Get
            Set
                Me("UsuarioOrigem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TECONDI")>  _
        Public Property SenhaOrigem() As String
            Get
                Return CType(Me("SenhaOrigem"),String)
            End Get
            Set
                Me("SenhaOrigem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MSSQL")>  _
        Public Property BaseDestino() As String
            Get
                Return CType(Me("BaseDestino"),String)
            End Get
            Set
                Me("BaseDestino") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("186.202.128.118")>  _
        Public Property ServidorDestino() As String
            Get
                Return CType(Me("ServidorDestino"),String)
            End Get
            Set
                Me("ServidorDestino") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("bd_ad_02")>  _
        Public Property SchemaDestino() As String
            Get
                Return CType(Me("SchemaDestino"),String)
            End Get
            Set
                Me("SchemaDestino") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BD_AD_02")>  _
        Public Property UsuarioDestino() As String
            Get
                Return CType(Me("UsuarioDestino"),String)
            End Get
            Set
                Me("UsuarioDestino") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("bd_ad_02@02")>  _
        Public Property SenhaDestino() As String
            Get
                Return CType(Me("SenhaDestino"),String)
            End Get
            Set
                Me("SenhaDestino") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ECOPORTO")>  _
        Public Property TabelaDestino() As String
            Get
                Return CType(Me("TabelaDestino"),String)
            End Get
            Set
                Me("TabelaDestino") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property IntervaloMin() As Integer
            Get
                Return CType(Me("IntervaloMin"),Integer)
            End Get
            Set
                Me("IntervaloMin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Eve_01() As Boolean
            Get
                Return CType(Me("Eve_01"),Boolean)
            End Get
            Set
                Me("Eve_01") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Eve_02() As Boolean
            Get
                Return CType(Me("Eve_02"),Boolean)
            End Get
            Set
                Me("Eve_02") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Eve_03() As Boolean
            Get
                Return CType(Me("Eve_03"),Boolean)
            End Get
            Set
                Me("Eve_03") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Eve_04() As Boolean
            Get
                Return CType(Me("Eve_04"),Boolean)
            End Get
            Set
                Me("Eve_04") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Eve_05() As Boolean
            Get
                Return CType(Me("Eve_05"),Boolean)
            End Get
            Set
                Me("Eve_05") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Eve_06() As Boolean
            Get
                Return CType(Me("Eve_06"),Boolean)
            End Get
            Set
                Me("Eve_06") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Eve_07() As Boolean
            Get
                Return CType(Me("Eve_07"),Boolean)
            End Get
            Set
                Me("Eve_07") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Eve_08() As Boolean
            Get
                Return CType(Me("Eve_08"),Boolean)
            End Get
            Set
                Me("Eve_08") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Eve_09() As Boolean
            Get
                Return CType(Me("Eve_09"),Boolean)
            End Get
            Set
                Me("Eve_09") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Eve_10() As Boolean
            Get
                Return CType(Me("Eve_10"),Boolean)
            End Get
            Set
                Me("Eve_10") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Eve_11() As Boolean
            Get
                Return CType(Me("Eve_11"),Boolean)
            End Get
            Set
                Me("Eve_11") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OraOLEDB.ORACLE")>  _
        Public Property ProvedorOrigem() As String
            Get
                Return CType(Me("ProvedorOrigem"),String)
            End Get
            Set
                Me("ProvedorOrigem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ProvedorDestino() As String
            Get
                Return CType(Me("ProvedorDestino"),String)
            End Get
            Set
                Me("ProvedorDestino") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.GeraEventosNAd02.My.MySettings
            Get
                Return Global.GeraEventosNAd02.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
